ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'BULL_RESEARCHER';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'BEAR_RESEARCHER';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'TRADER_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'AGGRESSIVE_RISK';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'NEUTRAL_RISK';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'CONSERVATIVE_RISK';
