ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'MACRO_ANALYST';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'SENTIMENT_ANALYST';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'QUANT_ANALYST';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'CRYPTO_SPECIALIST';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'TEAM_LEAD';

CREATE TYPE "OrderType" AS ENUM ('MARKET', 'LIMIT', 'STOP');

ALTER TABLE "DemoAccount" ADD COLUMN "ownerKey" TEXT NOT NULL DEFAULT 'demo';
CREATE UNIQUE INDEX "DemoAccount_ownerKey_key" ON "DemoAccount"("ownerKey");

ALTER TABLE "Trade" ADD COLUMN "orderType" "OrderType" NOT NULL DEFAULT 'MARKET';
ALTER TABLE "Trade" ADD COLUMN "requestedPrice" DOUBLE PRECISION;
